### ISSUE TITLE
lets-chat on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by macbroadcast** [sdelements/lets-chat#367]
hey there, awsome app :heart_eyes:

So I installed lets-chat without any problems on my local ubuntu machine (14.10 ) (node v0.10.32, npm 1.4.28, mongodb version v2.6.5, Python 2.7.8 )

but trying to install on Ubuntu 14.04.1 LTS droplet (node v0.10.32,npm 1.4.28, mongodb version v3.0.1, Python 2.7.6 ) gives me an: 

```javascript
#:~/lets-chat# npm start

> lets-chat@0.3.8 prestart /root/lets-chat
> migroose


/root/lets-chat/node_modules/migroose/node_modules/underscore/underscore.js:386
});
^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/lets-chat/node_modules/migroose/migroose/migration.js:4:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! lets-chat@0.3.8 prestart: `migroose`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.8 prestart script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root/lets-chat
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/lets-chat/npm-debug.log
npm ERR! not ok code 0

```

This is the  npm-debug.log http://pastebin.com/x5WbZ2k3

What could be wrong :blush: ?

Thanks

**Comment by hhaidar** [comment]
try reinstalling your node_modules:

```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by macbroadcast** [comment]
thanks strange ....```javascript
#:~/lets-chat# rm -rf node_modules
#:~/lets-chat# npm cache clean
#:~/lets-chat# sudo npm install
npm WARN engine mongoose-validate@0.0.5: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
#:~/lets-chat# npm start

> lets-chat@0.3.8 prestart /root/lets-chat
> migroose


module.js:340
    throw err;
          ^
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/lets-chat/node_modules/migroose/migroose/migration.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! lets-chat@0.3.8 prestart: `migroose`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.8 prestart script.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root/lets-chat
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/lets-chat/npm-debug.log
npm ERR! not ok code 0
```

**Comment by hhaidar** [comment]
Strange indeed. Seems like some dependencies are still missing :(

Try `npm install rsvp` and see if it runs. If not, give upgrading npm a shot via `npm install -g npm`

**Comment by hhaidar** [comment]
Also it's not recommended to run this as root!

**Comment by fallacy321** [comment]
Hi @macbroadcast since you are using ubuntu 14.04, try $sudo npm update rsvp 
Let me know if you are able to fix it ?

**Comment by macbroadcast** [comment]
I tryed anything, installed all the missing modules , rsvp and underscore but it end up with "Error: Cannot find module './lib/' " I have the same problem with another installation, works fine on my local ubuntu 14.10 but failed on digital ocean droplet with 14.04 LTS

**Comment by hhaidar** [comment]
@macbroadcast what version of npm are you running now?

**Comment by macbroadcast** [comment]
@hhaidar  npm version 2.7.3

**Comment by hhaidar** [comment]
@macbroadcast yea I'm really not sure what's going on :(

Maybe one last shot:

```
rm -rf node_modules
rm -rf ~/.npm
npm cache clean
npm install
``

Also have you tried running this as non-root?

**Comment by macbroadcast** [comment]
Tried removing the node_modules/ npm remove /clean cache and with non-root, thanks for your help , i give up for now.
```
macbroadcast@wordpress:~$ ls
macbroadcast@wordpress:~$ git clone https://github.com/sdelements/lets-chat.git
Cloning into 'lets-chat'...
remote: Counting objects: 10654, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10654 (delta 2), reused 0 (delta 0), pack-reused 10645
Receiving objects: 100% (10654/10654), 20.60 MiB | 5.41 MiB/s, done.
Resolving deltas: 100% (5915/5915), done.
Checking connectivity... done.
macbroadcast@wordpress:~$ mongod --version
db version v3.0.1
git version: 534b5a3f9d10f00cd27737fbcd951032248b5952
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
macbroadcast@wordpress:~$ ls
lets-chat
macbroadcast@wordpress:~$ cd lets-chat
macbroadcast@wordpress:~/lets-chat$ npm install
npm WARN engine mongoose-validate@0.0.5: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.7.3"})
Killed
macbroadcast@wordpress:~/lets-chat$ npm start

> lets-chat@0.3.8 prestart /home/macbroadcast/lets-chat
> migroose


module.js:340
    throw err;
          ^
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/macbroadcast/lets-chat/node_modules/migroose/migroose/migration.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Linux 3.13.0-36-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.32
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.8 prestart: `migroose`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.8 prestart script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/macbroadcast/lets-chat/npm-debug.log
macbroadcast@wordpress:~/lets-chat$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.3
3 info using node@v0.10.32
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart lets-chat@0.3.8
6 verbose unsafe-perm in lifecycle true
7 info lets-chat@0.3.8 Failed to exec prestart script
8 verbose stack Error: lets-chat@0.3.8 prestart: `migroose`
8 verbose stack Exit status 8
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:98:17)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:98:17)
8 verbose stack     at maybeClose (child_process.js:756:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
9 verbose pkgid lets-chat@0.3.8
10 verbose cwd /home/macbroadcast/lets-chat
11 error Linux 3.13.0-36-generic
12 error argv "node" "/usr/local/bin/npm" "start"
13 error node v0.10.32
14 error npm  v2.7.3
15 error code ELIFECYCLE
16 error lets-chat@0.3.8 prestart: `migroose`
16 error Exit status 8
17 error Failed at the lets-chat@0.3.8 prestart script 'migroose'.
17 error This is most likely a problem with the lets-chat package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     migroose
17 error You can get their info via:
17 error     npm owner ls lets-chat
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
macbroadcast@wordpress:~/lets-chat$ 
```

**Comment by necramirez** [comment]
```
macbroadcast@wordpress:~/lets-chat$ npm install
npm WARN engine mongoose-validate@0.0.5: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"2.7.3"})
Killed
```
^ this looks strange, no?  Did you accidentally Ctrl-C or something?

**Comment by necramirez** [comment]
I did the same commands you did on my Ubuntu 14.04.2 LTS, and I was able to `npm install` successfully as non-root user.

**Comment by Peque** [comment]
@macbroadcast: I managed to make it work in Ubuntu 14.04.2 LTS server, installing a more recent version of Node.js with a PPA maintained by NodeSource.

    curl -sL https://deb.nodesource.com/setup | sudo bash -
    sudo apt-get install nodejs

**Comment by macbroadcast** [comment]
@Peque Thank you very much ! i will try on the weekend.

**Comment by macbroadcast** [comment]
W000t - I found a nice manual https://mborgerson.com/setting-up-lets-chat-on-ubuntu/ and i have no errors anymore,i think it was caused by the missing node legacy package, but i need to change the port from default  5000 to e.g. 3000 what do i need to change ? Thanks

**Comment by hhaidar** [comment]
@macbroadcast nice. You can change the port in settings.yml
